# Generated by Django 5.1.7 on 2025-04-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_id",
            new_name="user",
        ),
    ]
