name: Question
description: 구현 중 궁금한 점이나 명확하지 않은 내용을 공유하세요.
title: "[QUESTION] 질문 제목 작성"
labels: [question]
assignees: []

body:
  - type: input
    id: topic
    attributes:
      label: 질문 주제
      description: 어떤 주제에 대한 질문인지 간단히 알려주세요.
      placeholder: 예) API 응답 처리 방식
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 질문 내용
      description: 궁금한 점을 최대한 구체적으로 작성해주세요.
      placeholder: |
        현재 로그인 API 호출 시 응답 데이터를 어디에서 처리하는 게 좋은지 궁금합니다.
        - views.py 내부 처리?
        - service 레이어에서 처리?

        다른 팀원들의 의견이 궁금합니다!
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 배경/상황 설명
      description: 왜 이 질문을 하게 되었는지 상황을 설명해주세요.
      placeholder: 예) 로그인 기능 리팩터링 중, 처리 책임 범위를 명확히 하고 싶어서 질문 드립니다.

  - type: checkboxes
    id: tags
    attributes:
      label: 관련 태그
      description: 어떤 영역에 관련된 질문인지 선택하세요.
      options:
        - label: 백엔드
        - label: 프론트엔드
        - label: 인프라
        - label: 프로젝트 구조
        - label: 기타

  - type: dropdown
    id: urgency
    attributes:
      label: 긴급도
      options:
        - 낮음 (언제든 답변 가능)
        - 보통 (며칠 내로 확인되면 좋음)
        - 높음 (빨리 해결이 필요함)
    validations:
      required: true
