# Generated by Django 5.1.7 on 2025-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trader", models.IntegerField()),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "transaction_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "transaction_details",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")]
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ]
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
