# Generated by Django 5.1.7 on 2025-04-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trader", models.IntegerField()),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "transaction_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "transaction_details",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        default="DEPOSIT",
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        default="ATM",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.account",
                    ),
                ),
            ],
        ),
    ]
