# Generated by Django 5.1.7 on 2025-04-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_user_id_account_user"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="account.account",
            ),
            preserve_default=False,
        ),
    ]
