# Generated by Django 5.1.7 on 2025-04-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_method",
            field=models.CharField(
                choices=[
                    ("ATM", "ATM 거래"),
                    ("TRANSFER", "계좌이체"),
                    ("AUTOMATIC_TRANSFER", "자동이체"),
                    ("CARD", "카드결제"),
                    ("INTEREST", "이자"),
                ],
                default="ATM",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], default="DEPOSIT"
            ),
        ),
    ]
