# Generated by Django 5.1.7 on 2025-04-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_about",
                    models.CharField(
                        choices=[
                            ("TOTAL_SPENDING", "총 지출"),
                            ("TOTAL_INCOME", "총 수입"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "일간"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("YEARLY", "연간"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("analysis_description", models.CharField(default="", max_length=100)),
                ("result_image", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
