# Generated by Django 5.1.7 on 2025-04-03 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_about",
            field=models.CharField(
                choices=[("TOTAL_SPENDING", "총 지출"), ("TOTAL_INCOME", "총 수입")],
                default="TOTAL_SPENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "일간"),
                    ("WEEKLY", "주간"),
                    ("MONTHLY", "월간"),
                    ("YEARLY", "연간"),
                ],
                default="DAILY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="period_end",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="period_start",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result_image",
            field=models.TextField(default=""),
        ),
    ]
